### PR TITLE
dotCMS/core#11984 updated connectionTimeout property

### PR DESCRIPTION
**Pull request by joseorsini**
Tested on backported fix to 3.7.1 and using fixes from dotCMS/core#11913. Working as expected. 

See related ticket dotCMS/core#11984 for more details on how to test.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Comment by jgambarios** [comment]
@joseorsini this is just a 3.7.1 fix?, we don't need/want this for 4.x?

**Comment by jtesser** [comment]
@jgambarios I would say everywhere

**Comment by wezell** [comment]
I actually don't think so, I would not change this default value.  For high-performance webistes, I think the recommendation is to actually lower this to 2000 or 3000 so that connections can fail fast.

**Comment by wezell** [comment]
The 60 sec setting should only be applied if a customer is looking to support very slow or crappy connections, which I would argue is not a majority of our customers.  I would keep Tomcat's default to ship with and it can be tuned on a case by case basis.

**Comment by dotcmsCodeReview** [comment]
hummm.  it happens sometimes on just large downloads even with normal
speed.  For example it happened on the support site to Brent on friday

**Comment by jtesser** [comment]
I, JT am the code review BTW.  Sometimes my email works and others times
not :-p

**Pull request closed without merging**
